*this program creates the firm age;
*Here the first year is calculated for each gvkey2 and then this is merged with
the main data to calculate the firm age using this first year and nyear values;
libname tmp1 '\\apporto.com\dfs\SEA\Users\s116_sea\Desktop\FinANa\SAAS';
run;
data a1; set tmp1.Firm_age_dataset;
data a2; set a1;
if at="." then delete;
gvkey2=gvkey*1;
nyear=year(datadate);
proc sort nodupkey; by gvkey2 nyear;
*proc means; 
*proc print data=a2 (obs=200); *run;
data a3; set a2;
drop consol indfmt datafmt popsrc curcd costat tic fyear datadate;
*proc print data=a3 (obs=200); *run;
data a4; set a3;
proc sort; by gvkey2 nyear;
*proc print data=a4 (obs=200); *run;
data a5; set a4;
by gvkey2;
first=first.gvkey2;
run;
data a6; set a5;
*proc print data=a6 (obs=1000); *run;
if first=1;
if first=1 then firstyear=nyear;
keep gvkey2 firstyear;
*proc print data=a6 (obs=100); *run;

data a7; set a4;
keep gvkey2 nyear;
proc sort nodupkey; by gvkey2 nyear;
data a8; set a6;
proc sort nodupkey; by gvkey2 firstyear;
data a9;
merge a7 a8;
by gvkey2;
proc sort; by gvkey2 nyear;
data a10; set a9;
firmage = log(nyear-firstyear+1);
data a11; set a10;
proc print data=a11 (obs=100); run;
data tmp1.Firmage1; set a11;
data tmp1.Firmage2; set a11;
data tmp1.Firmage3; set a11;
data tmp1.Firmage4; set a11;
proc means; run;
